import Foundation

// Chei pentru direcția vizuală aprobată (traseu, dispozitive, incidente,
// raft). Tabel separat; `L.t` caută în toate. Verificat de
// `scripts/check-l10n.py` și `LocalizationTests`.
extension L {
    static let routeTable: [String: [AppLanguage: String]] = [
        // Ecrane
        "screen.prepare": [.ro: "Pregătire offload", .en: "Offload preparation", .es: "Preparación del offload"],
        "screen.prepare.sub": [.ro: "O singură citire a sursei, verificată pentru fiecare copie.", .en: "The source is read once and verified for every copy.", .es: "El origen se lee una vez y se verifica para cada copia."],
        "screen.transfer": [.ro: "Transfer în curs", .en: "Transfer in progress", .es: "Transferencia en curso"],
        "screen.result": [.ro: "Rezultat", .en: "Result", .es: "Resultado"],
        "action.startOffload": [.ro: "Pornește transferul", .en: "Start transfer", .es: "Iniciar transferencia"],
        "action.startHelp": [.ro: "Pornește (⌘↩). Avertismentele nu blochează pornirea.", .en: "Start (⌘↩). Warnings do not block starting.", .es: "Iniciar (⌘↩). Los avisos no bloquean el inicio."],
        "action.startBlocked": [.ro: "Pornirea e blocată de un incident critic — vezi coloana din dreapta.", .en: "Starting is blocked by a critical incident — see the right-hand column.", .es: "El inicio está bloqueado por un incidente crítico — mira la columna derecha."],

        // Dispozitive
        "device.cfexpress": [.ro: "Card CFexpress", .en: "CFexpress card", .es: "Tarjeta CFexpress"],
        "device.sdCard": [.ro: "Card SD", .en: "SD card", .es: "Tarjeta SD"],
        "device.memoryCard": [.ro: "Card de memorie", .en: "Memory card", .es: "Tarjeta de memoria"],
        "device.ssd": [.ro: "SSD extern", .en: "External SSD", .es: "SSD externo"],
        "device.hdd": [.ro: "HDD / RAID extern", .en: "External HDD / RAID", .es: "HDD / RAID externo"],
        "device.usbStick": [.ro: "Stick USB", .en: "USB flash drive", .es: "Memoria USB"],
        "device.internalVolume": [.ro: "Volum intern", .en: "Internal volume", .es: "Volumen interno"],
        "device.folder": [.ro: "Folder ales manual", .en: "Manually chosen folder", .es: "Carpeta elegida manualmente"],
        "device.externalDevice": [.ro: "Dispozitiv extern", .en: "External device", .es: "Dispositivo externo"],

        // Conexiuni
        "conn.usb": [.ro: "USB", .en: "USB", .es: "USB"],
        "conn.thunderbolt": [.ro: "Thunderbolt / PCIe", .en: "Thunderbolt / PCIe", .es: "Thunderbolt / PCIe"],
        "conn.sdReader": [.ro: "cititor SD", .en: "SD reader", .es: "lector SD"],
        "conn.sata": [.ro: "SATA", .en: "SATA", .es: "SATA"],
        "conn.internal": [.ro: "intern", .en: "internal", .es: "interno"],
        "conn.virtual": [.ro: "virtual / imagine disc", .en: "virtual / disk image", .es: "virtual / imagen de disco"],
        "conn.network": [.ro: "rețea", .en: "network", .es: "red"],

        // Motivul clasificării
        "why.folder": [.ro: "cale aleasă, nu rădăcina unui volum", .en: "chosen path, not a volume root", .es: "ruta elegida, no la raíz de un volumen"],
        "why.internal": [.ro: "stocarea internă a acestui Mac", .en: "this Mac's internal storage", .es: "almacenamiento interno de este Mac"],
        "why.network": [.ro: "volum de rețea", .en: "network volume", .es: "volumen de red"],
        "why.virtual": [.ro: "volum virtual sau imagine disc", .en: "virtual volume or disk image", .es: "volumen virtual o imagen de disco"],
        "why.sdReader": [.ro: "cititorul SD al Mac-ului", .en: "the Mac's SD reader", .es: "el lector SD del Mac"],
        "why.cameraCardModelCF": [.ro: "structură de cameră; cititorul raportează CFexpress", .en: "camera structure; the reader reports CFexpress", .es: "estructura de cámara; el lector indica CFexpress"],
        "why.cameraCardModelSD": [.ro: "structură de cameră; cititorul raportează SD", .en: "camera structure; the reader reports SD", .es: "estructura de cámara; el lector indica SD"],
        "why.cameraCard": [.ro: "structură de cameră pe mediu amovibil; tipul cardului nu e raportat", .en: "camera structure on removable media; card type not reported", .es: "estructura de cámara en soporte extraíble; tipo de tarjeta no indicado"],
        "why.usbRemovable": [.ro: "mediu amovibil pe USB", .en: "removable media on USB", .es: "soporte extraíble en USB"],
        "why.solidState": [.ro: "sistemul raportează mediu solid-state", .en: "the system reports solid-state media", .es: "el sistema indica soporte de estado sólido"],
        "why.rotational": [.ro: "sistemul raportează mediu rotațional", .en: "the system reports rotational media", .es: "el sistema indica soporte rotacional"],
        "why.nameHintHDD": [.ro: "indiciu din nume (tipul mediului nu e raportat)", .en: "hint from the name (media type not reported)", .es: "indicio por el nombre (tipo de soporte no indicado)"],
        "why.nameHintSSD": [.ro: "indiciu din nume (tipul mediului nu e raportat)", .en: "hint from the name (media type not reported)", .es: "indicio por el nombre (tipo de soporte no indicado)"],
        "why.nameHintCard": [.ro: "indiciu din nume, pe mediu amovibil", .en: "hint from the name, on removable media", .es: "indicio por el nombre, en soporte extraíble"],
        "why.unknown": [.ro: "sistemul nu raportează tipul", .en: "the system does not report the type", .es: "el sistema no indica el tipo"],
        "why.demo": [.ro: "date demo", .en: "demo data", .es: "datos de demostración"],

        // Insigne
        "badge.online": [.ro: "online", .en: "online", .es: "en línea"],
        "badge.offline": [.ro: "offline", .en: "offline", .es: "desconectado"],
        "badge.reading": [.ro: "citire", .en: "reading", .es: "leyendo"],
        "badge.writing": [.ro: "scriere", .en: "writing", .es: "escribiendo"],
        "badge.warning": [.ro: "avertisment", .en: "warning", .es: "aviso"],
        "role.source": [.ro: "SURSĂ", .en: "SOURCE", .es: "ORIGEN"],
        "role.sourceN": [.ro: "SURSA %d", .en: "SOURCE %d", .es: "ORIGEN %d"],
        "role.copyN": [.ro: "COPIA %d", .en: "COPY %d", .es: "COPIA %d"],

        // Traseu
        "route.slot.source": [.ro: "Trage aici un card, un disc sau un folder — sau alege din Dispozitive (clic dreapta)", .en: "Drop a card, drive or folder here — or pick one from Devices (right-click)", .es: "Suelta aquí una tarjeta, disco o carpeta — o elige en Dispositivos (clic derecho)"],
        "route.slot.destination": [.ro: "Trage aici discul pentru copia 1", .en: "Drop the drive for copy 1 here", .es: "Suelta aquí el disco para la copia 1"],
        "route.slot.addCopy": [.ro: "+ încă o copie (trage un disc aici)", .en: "+ another copy (drop a drive here)", .es: "+ otra copia (suelta un disco aquí)"],
        "route.remove": [.ro: "Scoate de pe traseu", .en: "Remove from route", .es: "Quitar de la ruta"],
        "node.prepare": [.ro: "Verificare în flux", .en: "In-stream verification", .es: "Verificación en flujo"],
        "node.rates": [.ro: "citire %@/s · scriere %@/s", .en: "read %@/s · write %@/s", .es: "lectura %@/s · escritura %@/s"],
        "node.eta": [.ro: "estimare: %@ rămase", .en: "estimate: %@ left", .es: "estimación: quedan %@"],

        "depth.short.sizeOnly": [.ro: "doar octeți", .en: "byte count only", .es: "solo bytes"],
        "depth.short.streamChecksum": [.ro: "checksum per copie", .en: "checksum per copy", .es: "checksum por copia"],
        "depth.short.readBack": [.ro: "checksum + recitire", .en: "checksum + re-read", .es: "checksum + relectura"],

        // Cifre
        "fig.toCopy": [.ro: "de copiat", .en: "to copy", .es: "por copiar"],
        "fig.measuring": [.ro: "se măsoară…", .en: "measuring…", .es: "midiendo…"],
        "fig.ofVolume": [.ro: "volum de %@", .en: "on a %@ volume", .es: "volumen de %@"],
        "fig.freeAfter": [.ro: "liberi după copie", .en: "free after copy", .es: "libres tras copiar"],
        "fig.missing": [.ro: "lipsă — nu încape", .en: "short — does not fit", .es: "faltan — no cabe"],
        "fig.usedOf": [.ro: "ocupat %@ din %@", .en: "%@ used of %@", .es: "%@ usados de %@"],
        "fig.unknownSpace": [.ro: "spațiu necunoscut", .en: "unknown space", .es: "espacio desconocido"],
        "fig.read": [.ro: "citiți", .en: "read", .es: "leídos"],
        "fig.written": [.ro: "scris", .en: "written", .es: "escrito"],
        "fig.confirmed": [.ro: "fișiere confirmate", .en: "files confirmed", .es: "archivos confirmados"],
        "fig.duration": [.ro: "durată %@", .en: "took %@", .es: "duración %@"],

        // Incidente
        "incidents.title": [.ro: "Incidente", .en: "Incidents", .es: "Incidentes"],
        "incidents.incomplete": [.ro: "Adaugă o sursă și cel puțin o copie", .en: "Add a source and at least one copy", .es: "Añade un origen y al menos una copia"],
        "incidents.blocked": [.ro: "Blocat: %d incident(e) critic(e)", .en: "Blocked: %d critical incident(s)", .es: "Bloqueado: %d incidente(s) crítico(s)"],
        "incidents.readyWarnings": [.ro: "Gata, cu %d avertisment(e)", .en: "Ready, with %d warning(s)", .es: "Listo, con %d aviso(s)"],
        "incidents.warningsDontBlock": [.ro: "Avertismentele nu blochează pornirea — sunt de știut înainte de a formata cardul.", .en: "Warnings do not block starting — they are worth knowing before formatting the card.", .es: "Los avisos no bloquean el inicio — conviene conocerlos antes de formatear la tarjeta."],
        "incidents.none": [.ro: "Fără incidente până acum", .en: "No incidents so far", .es: "Sin incidentes por ahora"],
        "incidents.count": [.ro: "%d incident(e)", .en: "%d incident(s)", .es: "%d incidente(s)"],
        "incidents.transferNote": [.ro: "Cifrele sunt măsurate; timpul rămas e o estimare din ritmul de până acum.", .en: "Figures are measured; time left is an estimate from the pace so far.", .es: "Las cifras son medidas; el tiempo restante es una estimación del ritmo actual."],
        "incident.actionPrefix": [.ro: "Acțiune:", .en: "Action:", .es: "Acción:"],
        "severity.blocking": [.ro: "Critic", .en: "Critical", .es: "Crítico"],
        "severity.warning": [.ro: "Avertisment", .en: "Warning", .es: "Aviso"],
        "severity.info": [.ro: "Informație", .en: "Information", .es: "Información"],
        "severity.ok": [.ro: "OK", .en: "OK", .es: "OK"],

        "incident.card.title": [.ro: "%@: structura cardului", .en: "%@: card structure", .es: "%@: estructura de la tarjeta"],
        "incident.card.cause": [.ro: "%@", .en: "%@", .es: "%@"],
        "incident.card.action": [.ro: "Verifică în cameră înainte de a formata cardul. Transferul copiază fișierele așa cum sunt.", .en: "Check in the camera before formatting the card. The transfer copies the files as they are.", .es: "Revisa en la cámara antes de formatear la tarjeta. La transferencia copia los archivos tal como están."],
        "incident.space.title": [.ro: "%@: spațiu insuficient", .en: "%@: not enough space", .es: "%@: espacio insuficiente"],
        "incident.space.cause": [.ro: "Lipsesc %@ pentru această copie (măsurat, fără marja de siguranță).", .en: "%@ missing for this copy (measured, without the safety margin).", .es: "Faltan %@ para esta copia (medido, sin margen de seguridad)."],
        "incident.space.action": [.ro: "Eliberează spațiu sau alege alt disc. Pornirea va cere confirmare.", .en: "Free up space or choose another drive. Starting will ask for confirmation.", .es: "Libera espacio o elige otro disco. El inicio pedirá confirmación."],
        "incident.sizeOnly.title": [.ro: "Verificare doar după numărul de octeți", .en: "Byte-count verification only", .es: "Verificación solo por número de bytes"],
        "incident.sizeOnly.cause": [.ro: "Fără checksum, un fișier corupt cu mărimea corectă trece neobservat.", .en: "Without a checksum, a corrupted file with the right size goes unnoticed.", .es: "Sin checksum, un archivo dañado con el tamaño correcto pasa desapercibido."],
        "incident.sizeOnly.action": [.ro: "Alege xxHash64 în Setări → Verificare.", .en: "Choose xxHash64 in Settings → Verification.", .es: "Elige xxHash64 en Ajustes → Verificación."],
        "incident.unknown.title": [.ro: "%@: tip de dispozitiv necunoscut", .en: "%@: unknown device type", .es: "%@: tipo de dispositivo desconocido"],
        "incident.unknown.cause": [.ro: "Sistemul nu raportează tipul mediului; e afișat ca dispozitiv extern. Transferul nu e afectat.", .en: "The system does not report the media type; it is shown as an external device. The transfer is not affected.", .es: "El sistema no indica el tipo de soporte; se muestra como dispositivo externo. La transferencia no se ve afectada."],
        "incident.resume.title": [.ro: "Folder existent la destinație", .en: "Existing folder at the destination", .es: "Carpeta existente en el destino"],
        "incident.resume.cause": [.ro: "%@ — la reluare, fișierele existente se recitesc și se compară cu sursa, nu se presupun corecte.", .en: "%@ — when resuming, existing files are re-read and compared with the source, never assumed correct.", .es: "%@ — al reanudar, los archivos existentes se releen y se comparan con el origen, nunca se dan por buenos."],
        "incident.disconnected.title": [.ro: "%@ s-a deconectat", .en: "%@ was disconnected", .es: "%@ se desconectó"],
        "incident.disconnected.cause": [.ro: "Destinația nu mai e montată. Fișierele rămase se marchează neconfirmate doar aici; celelalte copii continuă.", .en: "The destination is no longer mounted. Remaining files are marked unconfirmed only here; other copies continue.", .es: "El destino ya no está montado. Los archivos restantes se marcan sin confirmar solo aquí; las demás copias continúan."],
        "incident.disconnected.action": [.ro: "Reconectează discul și reia transferul la final; nu formata cardul.", .en: "Reconnect the drive and resume the transfer at the end; do not format the card.", .es: "Vuelve a conectar el disco y reanuda al final; no formatees la tarjeta."],
        "incident.failing.title": [.ro: "%@: %@ fișier(e) neconfirmate", .en: "%@: %@ file(s) not confirmed", .es: "%@: %@ archivo(s) sin confirmar"],
        "incident.failing.cause": [.ro: "Scriere sau verificare eșuată la această destinație (vezi jurnalul tehnic).", .en: "Write or verification failed at this destination (see the technical log).", .es: "Fallo de escritura o verificación en este destino (ver el registro técnico)."],
        "incident.failing.action": [.ro: "Reîncercarea automată rulează la final, dacă e activă.", .en: "The automatic retry runs at the end, if enabled.", .es: "El reintento automático se ejecuta al final, si está activado."],
        "incident.unconfirmed.title": [.ro: "%@: %@ fișier(e) neconfirmate", .en: "%@: %@ file(s) not confirmed", .es: "%@: %@ archivo(s) sin confirmar"],
        "incident.unconfirmed.cause": [.ro: "Aceste fișiere nu au o copie verificată la această destinație.", .en: "These files have no verified copy at this destination.", .es: "Estos archivos no tienen copia verificada en este destino."],
        "incident.unconfirmed.action": [.ro: "Nu formata cardul. Deschide raportul CSV și reia transferul.", .en: "Do not format the card. Open the CSV report and resume the transfer.", .es: "No formatees la tarjeta. Abre el informe CSV y reanuda la transferencia."],
        "incident.recovered.title": [.ro: "%@: %@ fișier(e) recuperate la reîncercare", .en: "%@: %@ file(s) recovered on retry", .es: "%@: %@ archivo(s) recuperados al reintentar"],
        "incident.recovered.cause": [.ro: "Au eșuat prima dată și au fost confirmate la reîncercare.", .en: "They failed the first time and were confirmed on retry.", .es: "Fallaron la primera vez y se confirmaron al reintentar."],
        "incident.recovered.action": [.ro: "Verifică cablul, cititorul și discul înainte de următorul card.", .en: "Check the cable, reader and drive before the next card.", .es: "Revisa el cable, el lector y el disco antes de la próxima tarjeta."],
        "incident.cancelled.title": [.ro: "%@: transfer oprit", .en: "%@: transfer stopped", .es: "%@: transferencia detenida"],
        "incident.cancelled.cause": [.ro: "Transferul a fost anulat înainte de final.", .en: "The transfer was cancelled before the end.", .es: "La transferencia se canceló antes del final."],
        "incident.cancelled.action": [.ro: "Pornește din nou pentru a relua; fișierele deja scrise se recitesc și se compară.", .en: "Start again to resume; files already written are re-read and compared.", .es: "Inicia de nuevo para reanudar; los archivos ya escritos se releen y comparan."],

        // Cauze și acțiuni pentru verificările de preflight
        "incident.cause.noSources": [.ro: "Traseul nu are încă o sursă.", .en: "The route has no source yet.", .es: "La ruta aún no tiene origen."],
        "incident.action.noSources": [.ro: "Trage cardul pe traseu.", .en: "Drop the card on the route.", .es: "Suelta la tarjeta en la ruta."],
        "incident.cause.noDestinations": [.ro: "Traseul nu are încă nicio copie.", .en: "The route has no copy yet.", .es: "La ruta aún no tiene copias."],
        "incident.action.noDestinations": [.ro: "Trage cel puțin un disc pe traseu.", .en: "Drop at least one drive on the route.", .es: "Suelta al menos un disco en la ruta."],
        "incident.cause.sourceMissing": [.ro: "Calea sursei nu mai există.", .en: "The source path no longer exists.", .es: "La ruta del origen ya no existe."],
        "incident.action.sourceMissing": [.ro: "Reintrodu cardul sau scoate-l de pe traseu.", .en: "Reinsert the card or remove it from the route.", .es: "Vuelve a insertar la tarjeta o quítala de la ruta."],
        "incident.cause.destinationMissing": [.ro: "Calea destinației nu mai există.", .en: "The destination path no longer exists.", .es: "La ruta del destino ya no existe."],
        "incident.action.destinationMissing": [.ro: "Reconectează discul sau scoate-l de pe traseu.", .en: "Reconnect the drive or remove it from the route.", .es: "Vuelve a conectar el disco o quítalo de la ruta."],
        "incident.cause.destinationNotWritable": [.ro: "Sistemul nu permite scrierea aici (drepturi sau format doar-citire).", .en: "The system does not allow writing here (permissions or read-only format).", .es: "El sistema no permite escribir aquí (permisos o formato de solo lectura)."],
        "incident.action.destinationNotWritable": [.ro: "Verifică drepturile și „Acces total la disc” sau alege alt disc.", .en: "Check permissions and Full Disk Access, or choose another drive.", .es: "Revisa los permisos y el Acceso total al disco, o elige otro disco."],
        "incident.cause.destinationNotDirectory": [.ro: "Destinația e un fișier, nu un folder.", .en: "The destination is a file, not a folder.", .es: "El destino es un archivo, no una carpeta."],
        "incident.action.destinationNotDirectory": [.ro: "Alege un folder sau un disc.", .en: "Choose a folder or a drive.", .es: "Elige una carpeta o un disco."],
        "incident.cause.destinationInsideSource": [.ro: "Copia s-ar scrie pe card, peste material.", .en: "The copy would be written onto the card, over the footage.", .es: "La copia se escribiría en la tarjeta, sobre el material."],
        "incident.action.destinationInsideSource": [.ro: "Alege un disc separat pentru copie.", .en: "Choose a separate drive for the copy.", .es: "Elige un disco separado para la copia."],
        "incident.cause.sourceInsideDestination": [.ro: "Sursa se află în folderul copiei; o reluare ar copia propria ieșire.", .en: "The source is inside the copy folder; a resume would copy its own output.", .es: "El origen está dentro de la carpeta de la copia; una reanudación copiaría su propia salida."],
        "incident.action.sourceInsideDestination": [.ro: "Alege o destinație în afara sursei.", .en: "Choose a destination outside the source.", .es: "Elige un destino fuera del origen."],
        "incident.cause.sameAsSource": [.ro: "Sursa și copia sunt același loc.", .en: "The source and the copy are the same place.", .es: "El origen y la copia son el mismo lugar."],
        "incident.action.sameAsSource": [.ro: "Alege alt disc pentru copie.", .en: "Choose another drive for the copy.", .es: "Elige otro disco para la copia."],
        "incident.cause.duplicateDestination": [.ro: "Aceeași destinație apare de două ori — ar fi o singură copie.", .en: "The same destination appears twice — it would be a single copy.", .es: "El mismo destino aparece dos veces — sería una sola copia."],
        "incident.action.duplicateDestination": [.ro: "Scoate duplicatul de pe traseu.", .en: "Remove the duplicate from the route.", .es: "Quita el duplicado de la ruta."],
        "incident.cause.nestedDestinations": [.ro: "O copie ar ajunge în interiorul alteia.", .en: "One copy would end up inside another.", .es: "Una copia acabaría dentro de otra."],
        "incident.action.nestedDestinations": [.ro: "Folosește destinații separate.", .en: "Use separate destinations.", .es: "Usa destinos separados."],
        "incident.cause.sameVolumeAsSource": [.ro: "Un singur disc defect ar pierde și sursa, și copia.", .en: "A single failed drive would lose both the source and the copy.", .es: "Un único disco averiado perdería el origen y la copia."],
        "incident.action.sameVolumeAsSource": [.ro: "Pentru siguranță, folosește un disc separat.", .en: "For safety, use a separate drive.", .es: "Por seguridad, usa un disco separado."],
        "incident.cause.symlinkSource": [.ro: "Sursa e un link; se copiază conținutul țintei lui.", .en: "The source is a link; its target's content is copied.", .es: "El origen es un enlace; se copia el contenido de su destino."],
        "incident.action.symlinkSource": [.ro: "Verifică dacă ținta e cea dorită.", .en: "Check that the target is the intended one.", .es: "Comprueba que el destino del enlace es el correcto."],

        "result.fig.files": [.ro: "%d fișiere confirmate în %d copii", .en: "%d files confirmed across %d copies", .es: "%d archivos confirmados en %d copias"],
        "result.fig.read": [.ro: "%@ citiți o singură dată din sursă", .en: "%@ read once from the source", .es: "%@ leídos una sola vez del origen"],
        "result.fig.mhl": [.ro: "MHL scris la fiecare copie", .en: "MHL written at every copy", .es: "MHL escrito en cada copia"],

        // Detectorul de card
        "card.clips": [.ro: "%d clip(uri)", .en: "%d clip(s)", .es: "%d clip(s)"],
        "card.warn.empty": [.ro: "Cardul pare gol — nu s-a găsit niciun fișier media.", .en: "The card looks empty — no media files were found.", .es: "La tarjeta parece vacía — no se encontró ningún archivo multimedia."],
        "card.warn.zeroBytes": [.ro: "Fișiere de 0 octeți (posibil clipuri incomplete): %@", .en: "0-byte files (possibly incomplete clips): %@", .es: "Archivos de 0 bytes (posibles clips incompletos): %@"],
        "card.warn.large": [.ro: "Card foarte mare — numărătoarea de clipuri e orientativă.", .en: "Very large card — the clip count is approximate.", .es: "Tarjeta muy grande — el recuento de clips es aproximado."],
        "card.warn.subfolder": [.ro: "%@ pare a fi un SUBFOLDER al cardului %@ — copiat singur, pierzi metadatele cardului.", .en: "%@ looks like a SUBFOLDER of card %@ — copied alone, the card's metadata is lost.", .es: "%@ parece una SUBCARPETA de la tarjeta %@ — copiada sola, se pierden los metadatos de la tarjeta."],

        // Raft și coadă
        "shelf.title": [.ro: "Dispozitive", .en: "Devices", .es: "Dispositivos"],
        "shelf.hint": [.ro: "Trage pe traseu sau clic dreapta pentru rol", .en: "Drag onto the route or right-click for a role", .es: "Arrastra a la ruta o clic derecho para un rol"],
        "shelf.useAsSource": [.ro: "Folosește ca sursă", .en: "Use as source", .es: "Usar como origen"],
        "shelf.useAsDestination": [.ro: "Adaugă ca copie", .en: "Add as copy", .es: "Añadir como copia"],
        "queue.titleShort": [.ro: "Coadă", .en: "Queue", .es: "Cola"],
        "queue.titleCount": [.ro: "Coadă (%d)", .en: "Queue (%d)", .es: "Cola (%d)"],

        // Galerie (DEBUG)
        "gallery.devices": [.ro: "Dispozitive", .en: "Devices", .es: "Dispositivos"],
        "gallery.scale": [.ro: "Scalare", .en: "Scale", .es: "Escala"],
        "gallery.badges": [.ro: "Insigne", .en: "Badges", .es: "Insignias"],
        "gallery.incidents": [.ro: "Incidente", .en: "Incidents", .es: "Incidentes"],
        "gallery.endpoints": [.ro: "Capete de traseu", .en: "Route endpoints", .es: "Extremos de la ruta"],
        "gallery.shelf": [.ro: "Raft", .en: "Shelf", .es: "Estante"],
    ]
}
